name: Pactify CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    # --- THIS IS THE DEFINITIVE FIX ---
    # This 'env' block securely passes your GitHub Secrets 
    # to the virtual machine as environment variables.
    env:
      NEXT_PUBLIC_CLERK_SIGN_IN_URL: ${{ secrets.NEXT_PUBLIC_CLERK_SIGN_IN_URL }}
      NEXT_PUBLIC_CLERK_SIGN_UP_URL: ${{ secrets.NEXT_PUBLIC_CLERK_SIGN_UP_URL }}
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
      CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      BACKEND_WALLET_PRIVATE_KEY: ${{ secrets.BACKEND_WALLET_PRIVATE_KEY }}
      SEPOLIA_RPC_URL: ${{ secrets.SEPOLIA_RPC_URL }}
      NEXT_PUBLIC_GOAL_STAKE_CONTRACT_ADDRESS: ${{ secrets.NEXT_PUBLIC_GOAL_STAKE_CONTRACT_ADDRESS }}
      # Add your Pacts contract address secret here too if you have one
      # NEXT_PUBLIC_PACTS_CONTRACT_ADDRESS: ${{ secrets.NEXT_PUBLIC_PACTS_CONTRACT_ADDRESS }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Lint Check
        run: npm run lint

      # The build step will now have access to the necessary keys
      - name: Run Build Check
        run: npm run build

      # The test step will now have access to all keys, allowing tests to pass
      - name: Run Playwright Tests
        run: npx playwright test